project:
  name: "ML Assignments â€“ PPGI - UFPB | 2025"
  author: "Lucas Dantas"
  seed: 42
  output_dir: "outputs/"
  data_dir: "data/"

dataset:
  generator: "bivariate_gaussian"

  params:
    n_class1: 150
    n_class2: 150
    mu1: [25.0, 10.0]
    mu2: [60.0, 30.0]
    var1: [100.0, 25.0]
    var2: [36.0, 144.0]
    random_state: 42

  test_size: 0.25
  shuffle: true
  normalize: false
